name: GitHub-VPS
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Ngrok və Giriş Ayarları
        run: |
          # Ngrok yüklənilir
          Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip
          
          # İstifadəçi yaradılır
          net user runneradmin "Vps12345!" /add
          net localgroup administrators runneradmin /add
          
          # Sənin Ngrok Tokenin bura yazıldı
          ./ngrok/ngrok.exe authtoken "3BcGhxJdpZFxKdIeYYhLTqoIYmJ_4kWcZoJk4xPmmVpVn8pNW"
          
          # Ngrok başladılır
          Start-Process ./ngrok/ngrok.exe -ArgumentList "tcp 3389"
          
          # 30 saniyə gözləyirik ki, tunel tam aktivləşsin
          Start-Sleep -Seconds 30

      - name: Qoşulma Ünvanını Ekrana Çıxar
        run: |
          # Tunel ünvanını çəkirik
          $url = (Invoke-WebRequest -Uri http://localhost:4040/api/tunnels -UseBasicParsing | ConvertFrom-Json).tunnels[0].public_url
          
          Write-Host "`n"
          Write-Host "=========================================="
          Write-Host "🚀 VPS ARTIQ HAZIRDIR!"
          Write-Host "🔗 ÜNVAN: $url"
          Write-Host "👤 İSTİFADƏÇİ: runneradmin"
          Write-Host "🔑 ŞİFRƏ: Vps12345!"
          Write-Host "=========================================="
          Write-Host "`n"

      - name: Canlı Saxla (6 Saat)
        run: |
          while($true) { Start-Sleep -Seconds 3600 }
